// <auto-generated />
namespace QAScraper.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewIdProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewIdProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201307041426061_NewIdProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
